<?php
// This file is part of the mod_certificatebeautiful plugin for Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

defined('MOODLE_INTERNAL') || die;

$string['modulename'] = 'Beautiful certificate';
$string['pluginname'] = 'Beautiful certificate';
$string['modulenameplural'] = 'Beautiful certificates';
$string['pluginadministration'] = 'Course certificate administration';

$string['select_a_model'] = 'Select a model';
$string['select_the_model'] = 'Select the model';
$string['manage_models'] = 'Manage certificate models';
$string['list_model'] = 'List of models';
$string['add_new_model'] = 'Add new model';
$string['save_model'] = 'Save model';
$string['create_model'] = 'Create model';
$string['new_model'] = 'New Model';
$string['model_name'] = 'Model name';
$string['model_name_missing'] = 'Model name is required';
$string['model_page_name'] = 'Page: {$a}';
$string['edit_this_page'] = 'Edit this certificate page';
$string['edit_page'] = 'Edit certificate page';
$string['using_this_page'] = 'Use this page';
$string['add_new_page'] = 'Add a new page to the certificate';
$string['pages_certificate'] = 'Certificate pages';
$string['create_after_model'] = 'First save the model before adding pages to the certificate';
$string['select_model'] = 'Select Model';
$string['select_model_preview'] = 'Select a pre-existing model';
$string['report'] = 'View generated certificates';
$string['download_my_certificate'] = 'Download my certificate';
$string['view_my_certificate'] = 'View my certificate in a new tab';
$string['preview_certificate'] = 'Certificate preview';
$string['create_at_certificate'] = 'Certificate for {$a}';

$string['course_certificates'] = 'Course Certificates';
$string['my_certificates'] = 'My Certificates';
$string['from_certificates'] = 'Certificates from student {$a}';

// Report.
$string['report_filename'] = 'Certificates generated by students';
$string['report_usernome'] = 'Student name';
$string['report_useremail'] = 'Student email';
$string['report_code'] = 'Certificate code';
$string['report_timecreated'] = 'Created at';
$string['report_view_certificate'] = 'View';
$string['report_delete_certificate'] = 'Delete';
$string['report_confirm_delete_certificate'] = 'Are you sure you want to delete this certificate?';
$string['report_deleted_certificate'] = 'Certificate deleted successfully!';

// Install.
$string['certificate-appreciation'] = 'Certificate of Appreciation';
$string['certificate-elegant'] = 'Elegant Certificate';
$string['certificate-golden'] = 'Golden Certificate';
$string['certificate-kids-animals'] = 'Diploma template for kids with animals';
$string['certificate-kids-child-medical'] = 'Abstract child-like medical certificate';
$string['certificate-kids-gradient-modern'] = 'Gradient modern certificate template';
$string['certificate-kids-hand-drawn'] = 'Hand drawn preschool graduation certificate';
$string['certificate-kids-pastel'] = 'Cute pastel education certificate';
$string['certificate-kids-template'] = 'Diploma template for kids';
$string['certificate-modern'] = 'Modern Certificate';
$string['certificate-simple'] = 'Simple Certificate';
$string['certificate-vintage'] = 'Vintage Certificate';
$string['sumary-secound-page'] = 'Summary Certificate';

// Certificate Model.
$string['certtitle'] = 'Certificate';
$string['certificado-subtitulo'] = 'OF COMPLETION';
$string['certpresented'] = 'This certificate is proudly presented to';
$string['certdate'] = 'Date';
$string['certsignature'] = 'Director';
$string['certificado-melhor'] = 'Best';
$string['certificado-curso'] = 'Course';
$string['certificado-descricao'] = 'This certificate certifies that the student <strong>{$USER->fullname}</strong> has successfully completed the <strong>{$course->fullname}</strong> with distinction, consolidating a comprehensive set of knowledge and skills essential for excelling in dynamic environments.';
$string['certificado-sumary'] = 'Summary';
$string['certificate_page_empty'] = 'Empty';

$string['help_certificate__name'] = 'User data';
$string['help_certificate_name'] = 'Certificate name';
$string['help_certificate_issue_timecreated'] = 'Certificate creation date.';
$string['help_certificate_issue_code'] = 'Unique code of the certificate.';

// User data.
$string['help_user__name'] = 'User data';
$string['help_user_id'] = 'Unique identifier for each user.';
$string['help_user_username'] = 'User\'s username.';
$string['help_user_idnumber'] = 'User\'s identification number.';
$string['help_user_firstname'] = 'User\'s first name.';
$string['help_user_lastname'] = 'User\'s last name.';
$string['help_user_middlename'] = 'User\'s middle name.';
$string['help_user_alternatename'] = 'User\'s alternative name.';
$string['help_user_fullname'] = 'User\'s full name, generated by the fullname() function.';
$string['help_user_email'] = 'User\'s email address.';
$string['help_user_phone1'] = 'User\'s primary phone number.';
$string['help_user_phone2'] = 'User\'s secondary phone number.';
$string['help_user_institution'] = 'User\'s institution.';
$string['help_user_department'] = 'User\'s department.';
$string['help_user_address'] = 'User\'s address.';
$string['help_user_city'] = 'User\'s city.';
$string['help_user_country'] = 'User\'s country code.';
$string['help_user_lang'] = 'User\'s preferred language.';
$string['help_user_calendartype'] = 'User\'s preferred calendar type.';
$string['help_user_timezone'] = 'User\'s preferred timezone.';
$string['help_user_firstaccess'] = 'Timestamp of the user\'s first access.';
$string['help_user_lastaccess'] = 'Timestamp of the user\'s last access.';
$string['help_user_lastlogin'] = 'Timestamp of the user\'s last login.';
$string['help_user_currentlogin'] = 'Timestamp of the user\'s current login.';
$string['help_user_lastip'] = 'IP address of the user\'s last access.';
$string['help_user_description'] = 'User\'s description.';
$string['help_user_timecreated'] = 'Timestamp of the user account creation.';
$string['help_user_timemodified'] = 'Timestamp of the last modification to the user account.';

$string['help_user_profile__name'] = 'User profile data';
$string['help_user_profile'] = 'Replace "NAME" with the user profile field';

// Course data.
$string['help_course__name'] = 'Data of the course for which the certificate is being generated';
$string['help_course_id'] = 'A unique identifier for each course.';
$string['help_course_category'] = 'The identifier of the category to which the course belongs.';
$string['help_course_fullname'] = 'The full name of the course.';
$string['help_course_shortname'] = 'A short name or unique code for the course.';
$string['help_course_summary'] = 'A brief summary or description of the course.';
$string['help_course_startdate'] = 'The start date of the course.';
$string['help_course_enddate'] = 'The end date of the course.';
$string['help_course_lang'] = 'The language of the course.';

// Moodle site data.
$string['help_site__name'] = 'Data of the Moodle instance for which the certificate is being generated';
$string['help_site_fullname'] = 'The full name of Moodle.';
$string['help_site_shortname'] = 'A short name for Moodle.';
$string['help_site_summary'] = 'A brief summary or description of Moodle.';

// Course category data.
$string['help_course_categories__name'] = 'Data of the course category for which the certificate is being generated';
$string['help_course_categories_id'] = 'Unique identifier of the course category.';
$string['help_course_categories_name'] = 'Name of the course category.';
$string['help_course_categories_idnumber'] = 'Unique identification number of the course category.';
$string['help_course_categories_description'] = 'Description of the course category.';
$string['help_course_categories_timemodified'] = 'Timestamp of the last modification to the course category.';

// Grade data.
$string['help_grade__name'] = 'Student\'s grade in the course';
$string['help_grade_finalgrade'] = 'Student\'s final grade';
$string['help_grade_table'] = 'Table with the student\'s grades';

// Teachers data.
$string['help_teachers__name'] = 'Teachers of the course';
$string['help_teachers_teacher1'] = 'Only the first teacher';
$string['help_teachers_teacher2'] = 'Only the first two teachers';
$string['help_teachers_teacherall'] = 'All teachers';

// Enrolments data.
$string['help_enrolments__name'] = 'Data of the student\'s enrollment in the course';
$string['help_enrolments_timestart'] = 'Date of the user\'s enrollment';

// Functions data.
$string['help_functions__name'] = 'Execute functions of the following Moodle and PHP native functions';
$string['help_functions_date'] = 'PHP <a href="https://php.net/date" target="_blank">date()</a> function';
$string['help_functions_userdate'] = 'Moodle <a href="https://moodledev.io/docs/apis/subsystems/time" target="_blank">userdate()</a> function';
$string['help_functions_time'] = 'PHP <a href="https://php.net/time" target="_blank">time()</a> function';

// Editor de Certificado.
$string['grapsjs-assetmanager-addbutton'] = 'Adicionar imagem';
$string['grapsjs-assetmanager-modaltitle'] = 'Selecionar imagem';
$string['grapsjs-assetmanager-uploadtitle'] = 'Solte os arquivos aqui ou clique para enviar';
$string['grapsjs-domcomponents-names-'] = 'Box';
$string['grapsjs-domcomponents-names-wrapper'] = 'Corpo';
$string['grapsjs-domcomponents-names-text'] = 'Texto';
$string['grapsjs-domcomponents-names-comment'] = 'Comentário';
$string['grapsjs-domcomponents-names-image'] = 'Imagem';
$string['grapsjs-domcomponents-names-video'] = 'Vídeo';
$string['grapsjs-domcomponents-names-label'] = 'Label';
$string['grapsjs-domcomponents-names-link'] = 'Link';
$string['grapsjs-domcomponents-names-map'] = 'Mapa';
$string['grapsjs-domcomponents-names-tfoot'] = 'Rodapé da tabela';
$string['grapsjs-domcomponents-names-tbody'] = 'Corpo da tabela';
$string['grapsjs-domcomponents-names-thead'] = 'Cabeçalho da tabela';
$string['grapsjs-domcomponents-names-table'] = 'Tabela';
$string['grapsjs-domcomponents-names-row'] = 'Linha da tabela';
$string['grapsjs-domcomponents-names-cell'] = 'Célula da tabela';
$string['grapsjs-domcomponents-names-section'] = 'Seção';
$string['grapsjs-domcomponents-names-body'] = 'Corpo';
$string['grapsjs-devicemanager-device'] = 'Dispositivo';
$string['grapsjs-devicemanager-devices-desktop'] = 'Desktop';
$string['grapsjs-devicemanager-devices-tablet'] = 'Tablet';
$string['grapsjs-devicemanager-devices-mobilelandscape'] = 'Celular, modo panorâmico';
$string['grapsjs-devicemanager-devices-mobileportrait'] = 'Celular, modo retrato';
$string['grapsjs-panels-buttons-titles-preview'] = 'Pré-visualização';
$string['grapsjs-panels-buttons-titles-fullscreen'] = 'Tela cheia';
$string['grapsjs-panels-buttons-titles-sw-visibility'] = 'Ver componentes';
$string['grapsjs-panels-buttons-titles-export-template'] = 'Ver código';
$string['grapsjs-panels-buttons-titles-open-sm'] = 'Abrir gerenciador de estilos';
$string['grapsjs-panels-buttons-titles-open-tm'] = 'Configurações';
$string['grapsjs-panels-buttons-titles-open-layers'] = 'Abrir gerenciador de camadas';
$string['grapsjs-panels-buttons-titles-open-blocks'] = 'Abrir blocos';
$string['grapsjs-selectormanager-label'] = 'Classes';
$string['grapsjs-selectormanager-selected'] = 'Selecionado';
$string['grapsjs-selectormanager-emptystate'] = '- Estado -';
$string['grapsjs-selectormanager-states-hover'] = 'Hover';
$string['grapsjs-selectormanager-states-active'] = 'Click';
$string['grapsjs-selectormanager-states-nth-of-type-2n'] = 'Even/Odd';
$string['grapsjs-stylemanager-empty'] = 'Selecione um elemento para usar o gerenciador de estilos';
$string['grapsjs-stylemanager-layer'] = 'Camada';
$string['grapsjs-stylemanager-filebutton'] = 'Imagens';
$string['grapsjs-stylemanager-sectors-general'] = 'Geral';
$string['grapsjs-stylemanager-sectors-layout'] = 'Disposição';
$string['grapsjs-stylemanager-sectors-typography'] = 'Tipografia';
$string['grapsjs-stylemanager-sectors-decorations'] = 'Decorações';
$string['grapsjs-stylemanager-sectors-extra'] = 'Extra';
$string['grapsjs-stylemanager-sectors-flex'] = 'Flex';
$string['grapsjs-stylemanager-sectors-dimension'] = 'Dimensão';
$string['grapsjs-stylemanager-properties-float'] = 'Float';
$string['grapsjs-stylemanager-properties-display'] = 'Exibição';
$string['grapsjs-stylemanager-properties-position'] = 'Posição';
$string['grapsjs-stylemanager-properties-top'] = 'Topo';
$string['grapsjs-stylemanager-properties-right'] = 'Direita';
$string['grapsjs-stylemanager-properties-left'] = 'Esquerda';
$string['grapsjs-stylemanager-properties-bottom'] = 'Inferior';
$string['grapsjs-stylemanager-properties-width'] = 'Largura';
$string['grapsjs-stylemanager-properties-height'] = 'Altura';
$string['grapsjs-stylemanager-properties-max-width'] = 'Largura Max.';
$string['grapsjs-stylemanager-properties-max-height'] = 'Altura Max.';
$string['grapsjs-stylemanager-properties-margin'] = 'Margem';
$string['grapsjs-stylemanager-properties-margin-top'] = 'Margem Superior';
$string['grapsjs-stylemanager-properties-margin-right'] = 'Margem a Direita';
$string['grapsjs-stylemanager-properties-margin-left'] = 'Margem a Esquerda';
$string['grapsjs-stylemanager-properties-margin-bottom'] = 'Margem Inferior';
$string['grapsjs-stylemanager-properties-padding'] = 'Padding';
$string['grapsjs-stylemanager-properties-padding-top'] = 'Padding Superior';
$string['grapsjs-stylemanager-properties-padding-left'] = 'Padding a Esquerda';
$string['grapsjs-stylemanager-properties-padding-right'] = 'Padding a Direita';
$string['grapsjs-stylemanager-properties-padding-bottom'] = 'Padding Inferior';
$string['grapsjs-stylemanager-properties-font-family'] = 'Font Family';
$string['grapsjs-stylemanager-properties-font-size'] = 'Tamanho da fonte';
$string['grapsjs-stylemanager-properties-font-weight'] = 'Espessura da fonte';
$string['grapsjs-stylemanager-properties-letter-spacing'] = 'Espaço entre letras';
$string['grapsjs-stylemanager-properties-color'] = 'Cor';
$string['grapsjs-stylemanager-properties-line-height'] = 'Altura da linha';
$string['grapsjs-stylemanager-properties-text-align'] = 'Alinhamento do texto';
$string['grapsjs-stylemanager-properties-text-shadow'] = 'Sombra do texto';
$string['grapsjs-stylemanager-properties-text-shadow-h'] = 'Sombra do texto: horizontal';
$string['grapsjs-stylemanager-properties-text-shadow-v'] = 'Sombra do texto: vertical';
$string['grapsjs-stylemanager-properties-text-shadow-blur'] = 'Desfoque da sombra do texto';
$string['grapsjs-stylemanager-properties-text-shadow-color'] = 'Cor da sombra da fonte';
$string['grapsjs-stylemanager-properties-border-top-left'] = 'Borda superior a esquerda';
$string['grapsjs-stylemanager-properties-border-top-right'] = 'Borda superior a direita';
$string['grapsjs-stylemanager-properties-border-bottom-left'] = 'Borda inferior a esquerda';
$string['grapsjs-stylemanager-properties-border-bottom-right'] = 'Borda inferior a direita';
$string['grapsjs-stylemanager-properties-border-radius-top-left'] = 'Raio da borda superior esquerda';
$string['grapsjs-stylemanager-properties-border-radius-top-right'] = 'Raio da borda superior direita';
$string['grapsjs-stylemanager-properties-border-radius-bottom-left'] = 'Raio da borda inferior esquerda';
$string['grapsjs-stylemanager-properties-border-radius-bottom-right'] = 'Raio da borda inferior direita';
$string['grapsjs-stylemanager-properties-border-radius'] = 'Raio da borda';
$string['grapsjs-stylemanager-properties-border'] = 'Borda';
$string['grapsjs-stylemanager-properties-border-width'] = 'Largura da borda';
$string['grapsjs-stylemanager-properties-border-style'] = 'Estilo da borda';
$string['grapsjs-stylemanager-properties-border-color'] = 'Cor da borda';
$string['grapsjs-stylemanager-properties-box-shadow'] = 'Sombra da box';
$string['grapsjs-stylemanager-properties-box-shadow-h'] = 'Sombra da box: horizontal';
$string['grapsjs-stylemanager-properties-box-shadow-v'] = 'Sombra da box: vertical';
$string['grapsjs-stylemanager-properties-box-shadow-blur'] = 'Desfoque da sombra da box';
$string['grapsjs-stylemanager-properties-box-shadow-spread'] = 'Extensão da sombra da box';
$string['grapsjs-stylemanager-properties-box-shadow-color'] = 'Cor da sombra da box';
$string['grapsjs-stylemanager-properties-box-shadow-type'] = 'Tipo de sombra da box';
$string['grapsjs-stylemanager-properties-background'] = 'Fundo';
$string['grapsjs-stylemanager-properties-background-color'] = 'Cor de fundo';
$string['grapsjs-stylemanager-properties-background-image'] = 'Imagem de fundo';
$string['grapsjs-stylemanager-properties-background-repeat'] = 'Repetir fundo';
$string['grapsjs-stylemanager-properties-background-position'] = 'Posição do fundo';
$string['grapsjs-stylemanager-properties-background-attachment'] = 'Plugin de fundo';
$string['grapsjs-stylemanager-properties-background-size'] = 'Tamanho do fundo';
$string['grapsjs-stylemanager-properties-transition'] = 'Transição';
$string['grapsjs-stylemanager-properties-transition-property'] = 'Tipo de transição';
$string['grapsjs-stylemanager-properties-transition-duration'] = 'Tempo de transição';
$string['grapsjs-stylemanager-properties-transition-timing-function'] = 'Função do tempo da transição';
$string['grapsjs-stylemanager-properties-perspective'] = 'Perspectiva';
$string['grapsjs-stylemanager-properties-transform'] = 'Transformação';
$string['grapsjs-stylemanager-properties-transform-rotate-x'] = 'Rotacionar horizontalmente';
$string['grapsjs-stylemanager-properties-transform-rotate-y'] = 'Rotacionar verticalmente';
$string['grapsjs-stylemanager-properties-transform-rotate-z'] = 'Rotacionar profundidade';
$string['grapsjs-stylemanager-properties-transform-scale-x'] = 'Escalar horizontalmente';
$string['grapsjs-stylemanager-properties-transform-scale-y'] = 'Escalar verticalmente';
$string['grapsjs-stylemanager-properties-transform-scale-z'] = 'Escalar profundidade';
$string['grapsjs-stylemanager-properties-flex-direction'] = 'Direção Flex';
$string['grapsjs-stylemanager-properties-flex-wrap'] = 'Flex wrap';
$string['grapsjs-stylemanager-properties-justify-content'] = 'Ajustar conteúdo';
$string['grapsjs-stylemanager-properties-align-items'] = 'Alinhar elementos';
$string['grapsjs-stylemanager-properties-align-content'] = 'Alinhar conteúdo';
$string['grapsjs-stylemanager-properties-order'] = 'Ordem';
$string['grapsjs-stylemanager-properties-flex-basis'] = 'Base Flex';
$string['grapsjs-stylemanager-properties-flex-grow'] = 'Crescimento Flex';
$string['grapsjs-stylemanager-properties-flex-shrink'] = 'Contração Flex';
$string['grapsjs-stylemanager-properties-align-self'] = 'Alinhar-se';
$string['grapsjs-traitmanager-empty'] = 'Selecione um elemento para usar o gerenciador de características';
$string['grapsjs-traitmanager-label'] = 'Configurações do componente';
$string['grapsjs-traitmanager-traits-options-target-false'] = 'Esta janela';
$string['grapsjs-traitmanager-traits-options-target-_blank'] = 'Nova janela';
$string['grapsjs-general'] = 'Gerais';
$string['grapsjs-dimensions'] = 'Dimensões';
$string['grapsjs-width'] = 'Largura';
$string['grapsjs-tipografia'] = 'Tipografia';
$string['grapsjs-decoration'] = 'Decorações';
$string['grapsjs-edit_code'] = 'Editar código';
$string['grapsjs-edit_code_paste_here_html'] = 'Cole aqui seu HTML/CSS e clique em Importar';
$string['grapsjs-repeat'] = 'Repetir';
$string['grapsjs-position'] = 'Posição';
$string['grapsjs-attachment'] = 'Anexo';
$string['grapsjs-size'] = 'Tamanho';
$string['grapsjs-certificate_page_save'] = 'Salvar página do certificado';
$string['grapsjs-show_border'] = 'Mostrar Bordas';
$string['grapsjs-preview'] = 'Prévia';
$string['grapsjs-fullscreen'] = 'Tela Cheia';
$string['grapsjs-undo'] = 'Desfazer';
$string['grapsjs-redo'] = 'Refazer';
$string['grapsjs-clear'] = 'Limpar o canvas';
$string['grapsjs-certificate_confirm_clear'] = 'Tem certeza de limpar o canvas?';
$string['grapsjs-open_sm'] = 'Gerenciador de Estilos';
$string['grapsjs-open_layers'] = 'Camadas';
$string['grapsjs-open_block'] = 'Blocos';
$string['grapsjs-settings'] = 'Configurações';