<?php

defined('MOODLE_INTERNAL') || die;

$string['modulename'] = 'Beautiful certificate';
$string['pluginname'] = 'Beautiful certificate';
$string['modulenameplural'] = 'Beautiful certificates';
$string['pluginadministration'] = 'Course certificate administration';

$string['select_a_model'] = 'Select a model';
$string['select_the_model'] = 'Select the model';
$string['manage_models'] = 'Manage certificate models';
$string['list_model'] = 'List of models';
$string['add_new_model'] = 'Add new model';
$string['save_model'] = 'Save model';
$string['create_model'] = 'Create model';
$string['new_model'] = 'New Model';
$string['model_name'] = 'Model name';
$string['model_name_missing'] = 'Model name is required';
$string['model_page_name'] = 'Page: {$a}';
$string['edit_this_page'] = 'Edit this certificate page';
$string['edit_page'] = 'Edit certificate page';
$string['using_this_page'] = 'Use this page';
$string['add_new_page'] = 'Add a new page to the certificate';
$string['pages_certificate'] = 'Certificate pages';
$string['create_after_model'] = 'First save the model before adding pages to the certificate';
$string['select_model'] = 'Select Model';
$string['select_model_preview'] = 'Select a pre-existing model';
$string['report'] = 'View generated certificates';
$string['download_my_certificate'] = 'Download my certificate';
$string['view_my_certificate'] = 'View my certificate in a new tab';
$string['preview_certificate'] = 'Certificate preview';
$string['create_at_certificate'] = 'Certificate for {$a}';

$string['course_certificates'] = 'Course Certificates';
$string['my_certificates'] = 'My Certificates';
$string['from_certificates'] = 'Certificates from student {$a}';

// Report
$string['report_filename'] = 'Certificates generated by students';
$string['report_usernome'] = 'Student name';
$string['report_useremail'] = 'Student email';
$string['report_code'] = 'Certificate code';
$string['report_timecreated'] = 'Created at';
$string['report_view_certificate'] = 'View';
$string['report_delete_certificate'] = 'Delete';
$string['report_confirm_delete_certificate'] = 'Are you sure you want to delete this certificate?';
$string['report_deleted_certificate'] = 'Certificate deleted successfully!';

// Install
$string['certificate-appreciation'] = 'Certificate of Appreciation';
$string['certificate-elegant'] = 'Elegant Certificate';
$string['certificate-modern'] = 'Modern Certificate';
$string['certificate-simple'] = 'Simple Certificate';
$string['certificate-vintage'] = 'Vintage Certificate';
$string['certificate-golden'] = 'Golden Certificate';
$string['sumary-secound-page'] = 'Summary Certificate';

// Certificate Model
$string['certificado-titulo'] = 'Certificate';
$string['certificado-subtitulo'] = 'OF COMPLETION';
$string['certificado-presented'] = 'This certificate is proudly presented to';
$string['certificado-date'] = 'On';
$string['certificado-signature'] = 'Director';
$string['certificado-melhor'] = 'Best';
$string['certificado-curso'] = 'Course';
$string['certificado-descricao'] = 'This certificate certifies that the student <strong>{$USER->fullname}</strong> has successfully completed the <strong>{$course->fullname}</strong> with distinction, consolidating a comprehensive set of knowledge and skills essential for excelling in dynamic environments.';
$string['certificado-sumary'] = 'Summary';
$string['certificate_page_empty'] = 'Empty';

$string['help_certificate__name'] = 'User data';
$string['help_certificate_name'] = 'Certificate name';
$string['help_certificate_issue_timecreated'] = 'Certificate creation date.';
$string['help_certificate_issue_code'] = 'Unique code of the certificate.';

// User data
$string['help_user__name'] = 'User data';
$string['help_user_id'] = 'Unique identifier for each user.';
$string['help_user_username'] = 'User\'s username.';
$string['help_user_idnumber'] = 'User\'s identification number.';
$string['help_user_firstname'] = 'User\'s first name.';
$string['help_user_lastname'] = 'User\'s last name.';
$string['help_user_middlename'] = 'User\'s middle name.';
$string['help_user_alternatename'] = 'User\'s alternative name.';
$string['help_user_fullname'] = 'User\'s full name, generated by the fullname() function.';
$string['help_user_email'] = 'User\'s email address.';
$string['help_user_phone1'] = 'User\'s primary phone number.';
$string['help_user_phone2'] = 'User\'s secondary phone number.';
$string['help_user_institution'] = 'User\'s institution.';
$string['help_user_department'] = 'User\'s department.';
$string['help_user_address'] = 'User\'s address.';
$string['help_user_city'] = 'User\'s city.';
$string['help_user_country'] = 'User\'s country code.';
$string['help_user_lang'] = 'User\'s preferred language.';
$string['help_user_calendartype'] = 'User\'s preferred calendar type.';
$string['help_user_timezone'] = 'User\'s preferred timezone.';
$string['help_user_firstaccess'] = 'Timestamp of the user\'s first access.';
$string['help_user_lastaccess'] = 'Timestamp of the user\'s last access.';
$string['help_user_lastlogin'] = 'Timestamp of the user\'s last login.';
$string['help_user_currentlogin'] = 'Timestamp of the user\'s current login.';
$string['help_user_lastip'] = 'IP address of the user\'s last access.';
$string['help_user_description'] = 'User\'s description.';
$string['help_user_timecreated'] = 'Timestamp of the user account creation.';
$string['help_user_timemodified'] = 'Timestamp of the last modification to the user account.';

$string['help_user_profile__name'] = 'User profile data';
$string['help_user_profile'] = 'Replace "NAME" with the user profile field';

// Course data
$string['help_course__name'] = 'Data of the course for which the certificate is being generated';
$string['help_course_id'] = 'A unique identifier for each course.';
$string['help_course_category'] = 'The identifier of the category to which the course belongs.';
$string['help_course_fullname'] = 'The full name of the course.';
$string['help_course_shortname'] = 'A short name or unique code for the course.';
$string['help_course_summary'] = 'A brief summary or description of the course.';
$string['help_course_startdate'] = 'The start date of the course.';
$string['help_course_enddate'] = 'The end date of the course.';
$string['help_course_lang'] = 'The language of the course.';

// Moodle site data
$string['help_site__name'] = 'Data of the Moodle instance for which the certificate is being generated';
$string['help_site_fullname'] = 'The full name of Moodle.';
$string['help_site_shortname'] = 'A short name for Moodle.';
$string['help_site_summary'] = 'A brief summary or description of Moodle.';

// Course category data
$string['help_course_categories__name'] = 'Data of the course category for which the certificate is being generated';
$string['help_course_categories_id'] = 'Unique identifier of the course category.';
$string['help_course_categories_name'] = 'Name of the course category.';
$string['help_course_categories_idnumber'] = 'Unique identification number of the course category.';
$string['help_course_categories_description'] = 'Description of the course category.';
$string['help_course_categories_timemodified'] = 'Timestamp of the last modification to the course category.';

// Grade data
$string['help_grade__name'] = 'Student\'s grade in the course';
$string['help_grade_finalgrade'] = 'Student\'s final grade';
$string['help_grade_table'] = 'Table with the student\'s grades';

// Teachers data
$string['help_teachers__name'] = 'Teachers of the course';
$string['help_teachers_teacher1'] = 'Only the first teacher';
$string['help_teachers_teacher2'] = 'Only the first two teachers';
$string['help_teachers_teacherall'] = 'All teachers';

// Enrolments data
$string['help_enrolments__name'] = 'Data of the student\'s enrollment in the course';
$string['help_enrolments_timestart'] = 'Date of the user\'s enrollment';

// Functions data
$string['help_functions__name'] = 'Execute functions of the following Moodle and PHP native functions';
$string['help_functions_date'] = 'PHP <a href="https://php.net/date" target="_blank">date()</a> function';
$string['help_functions_userdate'] = 'Moodle <a href="https://moodledev.io/docs/apis/subsystems/time" target="_blank">userdate()</a> function';
$string['help_functions_time'] = 'PHP <a href="https://php.net/time" target="_blank">time()</a> function';
