<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Language strings.
 *
 * @package    certificatebeautifuldatainfo_user
 * @copyright  2025 Eduardo Kraus https://eduardokraus.com/
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['address'] = 'User\'s address.';
$string['alternatename'] = 'User\'s alternative name.';
$string['calendartype'] = 'User\'s preferred calendar type.';
$string['city'] = 'User\'s city.';
$string['country'] = 'User\'s country code.';
$string['currentlogin'] = 'Timestamp of the user\'s current login.';
$string['department'] = 'User\'s department.';
$string['description'] = 'User\'s description.';
$string['email'] = 'User\'s email address.';
$string['firstaccess'] = 'Timestamp of the user\'s first access.';
$string['firstname'] = 'User\'s first name.';
$string['fullname'] = 'User\'s full name, generated by the fullname() function.';
$string['id'] = 'Unique identifier for each user.';
$string['idnumber'] = 'User\'s identification number.';
$string['institution'] = 'User\'s institution.';
$string['lang'] = 'User\'s preferred language.';
$string['lastaccess'] = 'Timestamp of the user\'s last access.';
$string['lastip'] = 'IP address of the user\'s last access.';
$string['lastlogin'] = 'Timestamp of the user\'s last login.';
$string['lastname'] = 'User\'s last name.';
$string['middlename'] = 'User\'s middle name.';
$string['phone1'] = 'User\'s primary phone number.';
$string['phone2'] = 'User\'s secondary phone number.';
$string['pluginname'] = 'User data';
$string['privacy:metadata'] = 'The plugin user does not store any personal data.';
$string['timecreated'] = 'Timestamp of the user account creation.';
$string['timemodified'] = 'Timestamp of the last modification to the user account.';
$string['timezone'] = 'User\'s preferred timezone.';
$string['username'] = 'User\'s username.';
